version: '3.8'

services:
  my-db:
    image: postgres:16
    container_name: postgres-container-my
    environment:
      POSTGRES_USER: hyoyoung
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hyoyoung_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name : redis-container
    ports:
      - "6379:6379"
  celery-worker:
    build:
      context: ./backend
    container_name: celery-worker-container
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: